### ISSUE TITLE
Make property initializers exclude-able

### ISSUE THREAD

**Issue by Newex** [Newex/PartialSourceGen#10]
Example:

```csharp
[Partial]
record Person
{
   [WithoutInitializer]
   public int Age { get; set; } = 0;
}
```

because the the generated code currently includes initializers:

```csharp
record PartialPerson
{
   public int? Age { get; set; } = 0;
}
```

Which means that

```csharp
PartialPerson updatePerson = new();

// Prints: The age is: 0
// Expected: The age is: null
Console.WriteLine("The age is: {0}", updatePerson.Age);
```

**Comment by Newex** [comment]
Or perhaps make the properties exclude the initializers by default, and only include them when specified...

Proposed usage:

```csharp
[Partial]
record Person
{
   [IncludeInitializer]
   public int Age { get; set; } = 0;
}
```

Then by default exclude all initializers

**Comment by Newex** [comment]
Implemented the opposite.

The current implementation (a2e076521b62010ae41297ec53a4571eb38a9317) is to by default exclude property initializers.

To include a property initializer one must opt-in using the `IncludeInitializer` attribute.

**Comment by rmja** [comment]
If we specify `IncludeInitializer` and the initialized value is not null, then it should probably become a not-null property in the partial?

**Comment by Newex** [comment]
Maybe I misunderstand, but the problem I see is this.

Imagine having a product class:

```csharp
public record Product
{
   public int ID { get; init; }
   public string Name { get; init; } = string.Empty;
   public string Description { get; init; } = string.Empty;
}
```

Which we designed to always have a name and a description. Then if create a partial of that in which the  property with initializers are not nullable like this:

```csharp
public record PartialProduct
{
   public int? ID { get; init; }
   public string Name { get; init; } = string.Empty;
   public string Description { get; init; } = string.Empty;
}
```

Then if I only want to update the Description of a product in a database/web api:

```csharp
// Somewhere in code -->
var productDescription = new PartialProduct
{
   ID = 123,
   Description = "The new description"
};
await Database.UpdateProduct(productDescription);

// More code -->
public async Task UpdateProduct(PartialProduct updates)
{
   var isNull = updates.Name is null;

   // Prints: "The name is null: false"
   Console.WriteLine("The name is null: {0}", isNull);
}
```

Because the name is not null, due to the property initializers, we cannot use the SQL functionality of (MSSQL, PostgreSQL) of `COALESCE` function when updating the record in the database.

What will happen in that case is: the product will update the name to an empty string. So now we have to write more code in c# to handle that case.

**Comment by rmja** [comment]
Currently, this:

```
[Partial]
public record Product
{
    [IncludeInitializer]
    public Dictionary<string, object> Attributes { get; set; } = [];
}
```

produces this:

```
public record PartialProduct
{
    public Dictionary<string, object>? Attributes { get; set; } = [];
}
```

That is probably what many want, but in my use case I need:

```
public record PartialProduct
{
    public Dictionary<string, object> Attributes { get; set; } = [];
}
```

Maybe the `IncludeInitializer` could have a boolean specifying whether the produced property should be nullable or not? I see this useful together with the new `PartialReference` attribute.

**Comment by Newex** [comment]
I have implemented the initial suggestion in v.0.0.12

The type will be non-nullable if the property has an `IncludeInitializer` attribute and the property is non-nullable.

Also this project is just ~5 days old, so we are probably the only users of this.

I don't know if this will  have any unforeseen consequences - hopefully not.
