### ISSUE TITLE
Generate also attributes

### ISSUE THREAD

**Issue by mperrando** [Newex/PartialSourceGen#15]
The class

```c#
    [Partial]
    public class TypeA
    {
        [Attribute1]
        [Attribute2("someArg")]
        public int MyField { get; set; }
    }
```

becomes
```c#
    public partial class PartialTypeA
    {
        public int? MyField { get; set; }
    }
```

but I would like to have also the attributes (all would be good, but maybe let specify which ones?) in the generated class
```c#
    public partial class PartialTypeA
    {
        [Attribute1]
        [Attribute2("someArg")]
        public int? MyField { get; set; }
    }
```

**Comment by mperrando** [comment]
@Newex added a test to better explain the issue in these  [branch](https://github.com/mperrando/PartialSourceGen/tree/attributes).

**Comment by Newex** [comment]
I am trying to imagine, how this can be done, so it is easy for the user.

My first idea is something like this:

```csharp
[Partial(IncludeExtraAttributes = true)]
public record Person
{
   [IncludeInitializer]
   public int ID { get; init; } = 123;
   [JsonPropertyName("myName")]
   public string Name { get; init; }
}
```

I am just worried how this will interact with, the other issue / feature request. As I understand the other request, they want to have the functionality to include inherited members.

Some preliminary thoughts: if those inherited members have attributes, how would I resolve the namespaces and is there anything we have to be cautious about...

**Comment by mperrando** [comment]
IncludeExtraAttributes sounds good. Honestly I do not get what the impact could be when the class/record inherits from another.

**Comment by Newex** [comment]
I have added that functionality, in the latest release v.0.0.17.

I also added tests for partial classes and inheritance.
