### ISSUE TITLE
Nested partials

### ISSUE THREAD

**Issue by rmja** [Newex/PartialSourceGen#9]
For example:

```C#

[Partial]
record Person {
   public List<Post> Posts { get; set; }
}

```

Is it possible to have the list be `List<PartialPost>`?

**Comment by Newex** [comment]
It should be possible, but I just started my journey on source generators, so I don't know how fast I can implement features.

It might be easier to mark the property like:

```csharp
[Partial]
record Person {
   [PartialReference]
   public List<Post> Posts { get; set; }
}
```

The only problem I see, is that a source generator cannot see other generated sources. So whether the `Posts` have any equivalent `PartialPosts` would be unknown. The responsibility to ensure that there exists a `PartialPost` should maybe be up to the user.

Although it seems that source generators can output anything, even wrong uncompilable code.

But I like the idea, and will look into it when I have time.

**Comment by Newex** [comment]
Added functionality to reference other partial entities.

```csharp
[Partial]
record Person {
   [PartialReference<Post, PartialPost>("PartialPosts")]
   public Dictionary<Post, List<Post>> Posts { get; set; }
}
```

produces:

```csharp
partial record PartialPerson {
   public Dictionary<PartialPost, List<PartialPost>>? PartialPosts { get; set; }
}
```

Thus every instance where the type is used should be replaced with the provided type.

Package version: v.0.0.10
